# Generated by Django 3.2 on 2022-08-31 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNPJModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNPJ', models.IntegerField(unique=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'CONDOMINIUM CNPJ',
                'verbose_name_plural': 'CONDOMINIUMS CNPJ',
            },
        ),
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Condominium name')),
                ('CNPJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cnpjmodel', verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'CONDOMINIUM NAME',
                'verbose_name_plural': 'CONDOMINIUM NAMES',
            },
        ),
        migrations.CreateModel(
            name='CondominiumInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70, verbose_name='Adress')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('owner', models.CharField(max_length=50, verbose_name='Owner')),
                ('CNPJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cnpjmodel', verbose_name='CNPJ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.namemodel')),
            ],
            options={
                'verbose_name': 'CONDOMINIUM CONTACT INFO',
                'verbose_name_plural': 'CONDOMINIUM CONTACT INFOS',
            },
        ),
    ]
