# Generated by Django 3.2 on 2022-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildcnpjmodel',
            name='CNPJ',
            field=models.IntegerField(verbose_name='CNPJ'),
        ),
    ]
