# Generated by Django 3.2 on 2022-08-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_buildcnpjmodel_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildcnpjmodel',
            name='name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.buildnamemodel'),
            preserve_default=False,
        ),
    ]
