# Generated by Django 3.2 on 2022-08-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220818_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildmodel',
            old_name='CNPJ',
            new_name='name_CNPJ',
        ),
        migrations.RemoveField(
            model_name='buildmodel',
            name='name',
        ),
    ]
